### ISSUE TITLE
Return non-zero exit status

### ISSUE THREAD

**Issue by fernandes** [dry-rb/dry-cli#47] opened 2018-12-06 11:19 UTC
Hi,

If I create a command and would like to automate the use of CLI, is there any way to return a non-zero exit status?

I tried the most intuitive way:

```ruby
def call(*)
  do_something
  return 3
end
```

but doesn't work, any tip on this? 😉

**Comment by davydovanton** [comment] 2018-12-06 13:31
hey, could you explain the problem? Why do you want to return specific data from CLI command and what (and where) do you expect to do with this data?

**Comment by fernandes** [comment] 2018-12-06 13:37
hey @davydovanton, first thank you for your reply, sure here we go..

unix consider exit code as 0 == run was ok, > 0 if any problem happened (maybe I'm not explaining correctly, here are the more details on [wikipedia](https://en.wikipedia.org/wiki/Exit_status#POSIX))

resuming, the idea is:

```bash
my_cli comand_will_succeed
echo $?
=> 0

my_cli command_will_fail
echo $?
=> X (X > 0, defined by the programmer)
```

so when automating the CLI call (using a shell script, puppet, whatever) can check if it was a success or not only by the exit code

thank you!

**Comment by davydovanton** [comment] 2018-12-06 13:39
got the point, thanks!

**Comment by EgorBazhenov** [comment] 2019-04-21 16:42
It seems to me that to solve this problem, we can try to return an object-result from the commands, which would know the return value and the exit-status.
I am not sure that this decision is worth it: major, rather bold revision.

If we trying to look at this issue in the general case, the problem is in exception-flow control, which may be like this:

```Ruby
def call
  # command code here
rescue SomeException => e
  logger.log_exception(e)
  exit(e.exit_code)
end
```
But in current data-flow, there are a callbacks, which can also raise an exceptions. So, here is my suggestion: add custom block to control exception-flow on whole chain `before -> main -> after`. I can make it, if this solutions looks normal.

**Comment by IvanShamatov** [comment] 2019-12-19 21:34
Closing this one since PR is present, the continued conversation is in #48

**Closed by IvanShamatov** 2019-12-19 21:34 UTC
